name: Main
on:
  - push
#   - workflow dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
#     services:
#       postgres:
#         image: postgres
# #         env:
# #           POSTGRES_PASSWORD: postgres
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5
    steps:
      - uses: actions/checkout@v2
#       - run: ./flyway --help
      - uses:  rahulmalewadi/flyway-custom-action@v1.0.0
        with:
          url: jdbc:snowflake://xz41255.ap-south-1.aws.snowflakecomputing.com/?db=FLYWAY&warehouse=COMPUTE_WH&role=ACCOUNTADMIN
          user: raghav_user
          password: abc123
#           locations: ./sql
      - run: ./flyway repair
      - run: ./flyway --help
      - run: echo 'testing'
